FROM odoo:{{odoo_version}}
LABEL maintainer={{git_email}}

# Switch to super user to perform privileged operatiosn
USER root

# Change this value to regenerate the whole image
ENV _UPDATED 2022-04-08

# Install missing useful stuff
RUN apt-get update && apt-get install -y git vim curl wget python3-wheel build-essential python3-dev libffi-dev

# Create needed paths
ENV PARTS_PATH /parts
ENV ROCCO_PATH /rocco
# This custom odoo data path is needed as the Odoo Docker images path causes issues when re-declared as volume in the composefile
ENV DATA_PATH /var/odoo
ENV PROJECT_ADDONS_PATH $PARTS_PATH/project_addons
ENV ENTERPRISE_PATH $PARTS_PATH/enterprise
# This path can be used to mount the submodule during development,
# before making them active on the remote repo
ENV DUMMY_SUBMODULE_PATH $PARTS_PATH/dummy_submodule
RUN mkdir -m 777 -p $DATA_PATH $ROCCO_PATH $PROJECT_ADDONS_PATH $ENTERPRISE_PATH $DUMMY_SUBMODULE_PATH
RUN chown -R odoo:odoo $ROCCO_PATH $PARTS_PATH $DATA_PATH

# Install Python libraries
ENV PIP_BREAK_SYSTEM_PACKAGES 1
COPY requirements.txt requirements.txt
RUN python3 -m pip install -r requirements.txt

# Switch back to the standard user
USER odoo

{%- if vcs == "github" %}
# Clone code from GitHub
RUN git clone --depth=1 -b {{addons_repo_branch}} https://{{github_token}}@github.com/{{github_addons_repo_user}}/{{github_addons_repo_name}}.git $PROJECT_ADDONS_PATH
{%- endif %}
{%- if vcs == "azure" %}
# Clone code from Azure DevOps
RUN git clone --depth=1 -b {{addons_repo_branch}} https://{{azure_token}}@dev.azure.com/{{ azure_addons_repo_organization }}/{{ azure_addons_repo_project }}/_git/{{ azure_addons_repo_name }} $PROJECT_ADDONS_PATH
{%- endif %}
{%- if include_enterprise == true %}
# Clone Odoo Enterprise from GitHub
RUN git clone --depth=1 -b {{odoo_version}} https://{{github_token}}@github.com/odoo/enterprise.git $ENTERPRISE_PATH
{%- endif %}
ADD bin/ $ROCCO_PATH/bin
{%- if vcs == "github" %}
RUN python3 $ROCCO_PATH/bin/submodules_processor.py $PROJECT_ADDONS_PATH {{github_token}}
{%- endif %}

# It looks like Python requirements must be installed as root, otherwise odoo (the software) won't see them if we install them as odoo (user) :-|
USER root
# Install Addons Repo Requirements, this will drill down and find all requirements files
RUN find "$PROJECT_ADDONS_PATH" -name "requirements.txt" -exec pip3 install -r {} \;
# Switch back to the standard user again
USER odoo

# Configure git, just in case
RUN git config --global user.email "{{git_email}}"; \
    git config --global user.name "{{git_name}}"

# Override the standard entry point to generate the odoo conf file at runtime
COPY ./entrypoint.sh /
